language: python
python:
    - "3.6.5"

install:
    - pip install -r requirements.txt

services:
    - postgresql

before_script:
    - psql -c "CREATE DATABASE questionerversion2;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres
    - export DATABASE="dbname=questionerversion2 host=localhost port=5432 user=postgres password=''"

script:
    - pytest
    - coverage run --source=app -m pytest && coverage report

after_success:
    - coveralls
